// flow-typed signature: 800eb6db4cd7193dd5fab8c36ac9af98
// flow-typed version: <<STUB>>/electron-packager_v^8.7.0/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'electron-packager'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'electron-packager' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'electron-packager/cli' {
  declare module.exports: any;
}

declare module 'electron-packager/common' {
  declare module.exports: any;
}

declare module 'electron-packager/ignore' {
  declare module.exports: any;
}

declare module 'electron-packager/infer' {
  declare module.exports: any;
}

declare module 'electron-packager/linux' {
  declare module.exports: any;
}

declare module 'electron-packager/mac' {
  declare module.exports: any;
}

declare module 'electron-packager/prune' {
  declare module.exports: any;
}

declare module 'electron-packager/targets' {
  declare module.exports: any;
}

declare module 'electron-packager/win32' {
  declare module.exports: any;
}

// Filename aliases
declare module 'electron-packager/cli.js' {
  declare module.exports: $Exports<'electron-packager/cli'>;
}
declare module 'electron-packager/common.js' {
  declare module.exports: $Exports<'electron-packager/common'>;
}
declare module 'electron-packager/ignore.js' {
  declare module.exports: $Exports<'electron-packager/ignore'>;
}
declare module 'electron-packager/index' {
  declare module.exports: $Exports<'electron-packager'>;
}
declare module 'electron-packager/index.js' {
  declare module.exports: $Exports<'electron-packager'>;
}
declare module 'electron-packager/infer.js' {
  declare module.exports: $Exports<'electron-packager/infer'>;
}
declare module 'electron-packager/linux.js' {
  declare module.exports: $Exports<'electron-packager/linux'>;
}
declare module 'electron-packager/mac.js' {
  declare module.exports: $Exports<'electron-packager/mac'>;
}
declare module 'electron-packager/prune.js' {
  declare module.exports: $Exports<'electron-packager/prune'>;
}
declare module 'electron-packager/targets.js' {
  declare module.exports: $Exports<'electron-packager/targets'>;
}
declare module 'electron-packager/win32.js' {
  declare module.exports: $Exports<'electron-packager/win32'>;
}
